---
- id: go-unit-tests
  name: 'go test'
  entry: pre-commit-hooks/go-unit-tests.sh
  types: [go]
  exclude: '(^|/)vendor/'
  language: 'script'
  description: "Runs `go test`. Requires golang: https://go.dev/doc/install"
  pass_filenames: false
- id: go-build
  name: 'go build'
  entry: pre-commit-hooks/go-build.sh
  types: [go]
  language: 'script'
  description: "Runs `go build`. Requires golang: https://go.dev/doc/install"
  pass_filenames: false
- id: go-generate
  name: 'go generate'
  entry: pre-commit-hooks/go-generate.sh
  types: [go]
  language: 'script'
  description: "Runs `go generate`. Requires golang: https://go.dev/doc/install"
  pass_filenames: true
- id: go-mod-tidy
  name: 'go mod tidy'
  entry: pre-commit-hooks/go-mod-tidy.sh
  types: [go]
  language: 'script'
  description: "Runs `go mod tidy -v`. Requires golang: https://go.dev/doc/install"
  pass_filenames: false
- id: go-mod-vendor
  name: 'go mod vendor'
  entry: pre-commit-hooks/go-mod-vendor.sh
  types: [go]
  language: 'script'
  description: "Runs `go mod vendor`. Requires golang: https://go.dev/doc/install"
  pass_filenames: false
