---
- id: go-fmt
  name: 'gofmt'
  entry: pre-commit-hooks/gofmt.sh
  types: [go]
  exclude: '(^|/)vendor/'
  language: 'script'
  description: "Runs `gofmt`. Requires golang: https://go.dev/doc/install"
  pass_filenames: true
- id: go-fumpt
  name: 'gofumpt'
  entry: pre-commit-hooks/go-fumpt.sh
  types: [go]
  exclude: '(^|/)vendor/'
  language: 'script'
  description: "Runs `gofumpt`. Requires gofumpt: https://github.com/mvdan/gofumpt"  # yamllint disable-line rule:line-length
  pass_filenames: true
- id: go-imports
  name: 'goimports'
  entry: pre-commit-hooks/go-imports.sh
  types: [go]
  exclude: '(^|/)vendor/'
  language: 'script'
  description: "Runs `goimports`. Requires goimports: https://pkg.go.dev/golang.org/x/tools/cmd/goimports"  # yamllint disable-line rule:line-length
  pass_filenames: true
- id: go-vet
  name: 'go vet'
  entry: pre-commit-hooks/go-vet.sh
  types: [go]
  exclude: '(^|/)vendor/'
  language: 'script'
  description: "Runs `go vet`. Requires golang: https://go.dev/doc/install"
  pass_filenames: true
- id: go-lint
  name: 'golint'
  entry: pre-commit-hooks/go-lint.sh
  types: [go]
  exclude: '(^|/)vendor/'
  language: 'script'
  description: "[DEPRECATED] Runs `golint`. Requires golint: https://github.com/golang/lint"  # yamllint disable-line rule:line-length
  pass_filenames: true
- id: golangci-lint
  name: 'golangci-lint'
  entry: pre-commit-hooks/golangci-lint.sh
  types: [go]
  exclude: '(^|/)vendor/'
  language: 'script'
  description: "Runs `golangci-lint`. Requires golangci-lint: https://github.com/golangci/golangci-lint"  # yamllint disable-line rule:line-length
  pass_filenames: true
- id: go-critic
  name: "gocritic"
  entry: pre-commit-hooks/go-critic.sh
  types: [go]
  exclude: '(^|/)vendor/'
  language: 'script'
  description: "Runs `gocritic`. Requires gocritic: https://github.com/go-critic/go-critic"  # yamllint disable-line rule:line-length
  pass_filenames: true
- id: go-unit-tests
  name: 'go test'
  entry: pre-commit-hooks/go-unit-tests.sh
  types: [go]
  exclude: '(^|/)vendor/'
  language: 'script'
  description: "Runs `go test`. Requires golang: https://go.dev/doc/install"
  pass_filenames: false
- id: go-build
  name: 'go build'
  entry: pre-commit-hooks/go-build.sh
  types: [go]
  language: 'script'
  description: "Runs `go build`. Requires golang: https://go.dev/doc/install"
  pass_filenames: false
- id: go-generate
  name: 'go generate'
  entry: pre-commit-hooks/go-build.sh
  types: [go]
  language: 'script'
  description: "Runs `go generate`. Requires golang: https://go.dev/doc/install"
  pass_filenames: true
- id: go-mod-tidy
  name: 'go mod tidy'
  entry: pre-commit-hooks/go-mod-tidy.sh
  types: [go]
  language: 'script'
  description: "Runs `go mod tidy -v`. Requires golang: https://go.dev/doc/install"  # yamllint disable-line rule:line-length
  pass_filenames: true
- id: go-mod-vendor
  name: 'go mod vendor'
  entry: pre-commit-hooks/go-mod-vendor.sh
  types: [go]
  language: 'script'
  description: "Runs `go mod vendor`. Requires golang: https://go.dev/doc/install"  # yamllint disable-line rule:line-length
  pass_filenames: false
